### ISSUE TITLE
DynamoDB scalability

### ISSUE THREAD

**Issue by tylermarien** [launchdarkly/go-server-sdk-dynamodb#24]
We are looking at using the DynamoDB integration for a big segments store. It appears there could be scaling issues due to the schema design. The issue is that the integration is using a constant string (ie. big_segments_user) for the partition key. This means that all items will be stored on one partition. Reads would then be limited by the partition limits (ie. 3000 RCU). DynamoDB recommends using a partition key with a high cardinality so that items can be spread across partitions and can scale much higher. Using something like the context hash key would be much better than using big_segments_user as the partition key. I am wondering if there are any plans to address this limitation.

Reference: https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/bp-partition-key-design.html

**Comment by cwaldren-ld** [comment]
Hi @tylermarien , acknowledging this issue. We are talking to you via support so I'll close this issue here.
